[versions]
agp = "8.12.2"
appcompatV7 = "28.0.0"
auth = "3.0.0"
authVersion = "3.0.0"
cardview = "1.0.0"
converterGson = "3.0.0"
converterGsonVersion = "3.0.0"
core = "13.0.0"
easypermissions = "3.0.0"
firebaseAuthVersion = "22.1.1"
firebaseBom = "34.6.0"
firebaseDatabaseVersion = "20.2.2"
firebaseFirestoreVersion = "24.8.1"
googleApiClient = "2.8.1"
googleApiClientAndroid = "2.8.1"
googleApiServicesYoutube = "v3-rev222-CL_1.25.0"
googleApiServicesYoutubeVersion = "v3-rev222-1.25.0"
googleHttpClientGson = "2.0.2"
googleOauthClientJetty = "1.39.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
loggingInterceptor = "5.3.0"
material = "1.12.0"
okhttp = "5.3.0"
playServicesAuth = "21.4.0"
googleGmsGoogleServices = "4.4.3"
firebaseAuth = "24.0.1"
firebaseStorage = "22.0.1"
recyclerview = "1.4.0"
retrofit = "3.0.0"
retrofitVersion = "3.0.0"
spotifyAppRemote = "0.8.0"
firebaseFirestore = "26.0.2"
spotifyAppRemoteRelease = "0.7.0"
firebaseDatabase = "22.0.1"
youtubeAndroidPlayerApi = "1.2.2"


[libraries]
appcompat-v7 = { module = "com.android.support:appcompat-v7", version.ref = "appcompatV7" }
auth = { module = "com.spotify.android:auth", version.ref = "auth" }
auth-v125 = { module = "com.spotify.android:auth", version.ref = "authVersion" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
com-google-firebase-firebase-auth = { module = "com.google.firebase:firebase-auth" }
com-google-firebase-firebase-auth2 = { module = "com.google.firebase:firebase-auth" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-gson-v290 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "core" }
easypermissions = { module = "pub.devrel:easypermissions", version.ref = "easypermissions" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth-v2211 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-database-v2022 = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabaseVersion" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-firestore-v2481 = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestoreVersion" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-services-youtube = { module = "com.google.apis:google-api-services-youtube", version.ref = "googleApiServicesYoutube" }
google-api-services-youtube-vv3rev2221250 = { module = "com.google.apis:google-api-services-youtube", version.ref = "googleApiServicesYoutubeVersion" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
google-http-client-gson = { module = "com.google.http-client:google-http-client-gson", version.ref = "googleHttpClientGson" }
google-oauth-client-jetty = { module = "com.google.oauth-client:google-oauth-client-jetty", version.ref = "googleOauthClientJetty" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-v290 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
spotify-app-remote = { module = "com.spotify.android:spotify-app-remote", version.ref = "spotifyAppRemote" }
com-google-firebase-firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
spotify-app-remote-release = { module = "com.spotify.android:spotify-app-remote-release", version.ref = "spotifyAppRemoteRelease" }
google-firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
youtube-android-player-api = { module = "com.google.android.youtube:youtube-android-player-api", version.ref = "youtubeAndroidPlayerApi" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

